# Preprocessing

### Importing Libraries

In [3]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
import math

In [4]:
df = pd.read_csv("heart.csv")
df.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
df.drop_duplicates(inplace=True)
df.describe()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,0.682119,0.963576,131.602649,246.500000,0.149007,0.526490,149.569536,0.327815,1.043046,1.397351,0.718543,2.314570,0.543046
std,9.04797,0.466426,1.032044,17.563394,51.753489,0.356686,0.526027,22.903527,0.470196,1.161452,0.616274,1.006748,0.613026,0.498970
min,29.00000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.00000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.250000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.50000,1.000000,1.000000,130.000000,240.500000,0.000000,1.000000,152.500000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,1.000000,2.000000,140.000000,274.750000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [6]:
X = df.drop('output',axis='columns')
y= df['output']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# K-Nearest Neighbors

In [8]:

knn = KNeighborsClassifier(n_neighbors= 5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print("k=5 ",(accuracy_score(y_test, y_pred)))

knn = KNeighborsClassifier(n_neighbors= 7)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print("k=7 ",(accuracy_score(y_test, y_pred)))

count_row = df.shape[0]
knn = KNeighborsClassifier(n_neighbors=math.ceil(math.sqrt(count_row)))
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print("sqrt(n) ",(accuracy_score(y_test, y_pred)))

k=5  0.5901639344262295
k=7  0.6229508196721312
sqrt(n)  0.6885245901639344

# Random Forest

In [9]:
rf_classifier = RandomForestClassifier(n_estimators = 3, criterion = 'entropy')
rf_classifier.fit(X_train, y_train)
y_pred_rf = rf_classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred_rf)

print("n_estimators = 3 ",(accuracy_score(y_test, y_pred_rf)))

rf_classifier = RandomForestClassifier(n_estimators = 5, criterion = 'entropy')
rf_classifier.fit(X_train, y_train)
y_pred_rf = rf_classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred_rf)

print("n_estimators = 5 ",(accuracy_score(y_test, y_pred_rf)))

rf_classifier = RandomForestClassifier(n_estimators = 7, criterion = 'entropy')
rf_classifier.fit(X_train, y_train)
y_pred_rf = rf_classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred_rf)

print("n_estimators = 7 ",(accuracy_score(y_test, y_pred_rf)))

n_estimators = 3  0.7868852459016393
n_estimators = 5  0.8360655737704918
n_estimators = 7  0.8360655737704918